name: 'Docs publisher'
description: 'Takes care of publishing documentation to the specified branch'
author: 'Marco Reni'
inputs:
  deployment-branch:
    description: 'The branch where the docs will be published'
    required: true
    default: 'gh-pages'
  docs-command:
    description: 'The command to be run inside the repository to create the docs'
    required: true
  docs-path:
    description: 'The path where documentation will be found once docs are created. Path is relative to the root of the project'
    required: true
  # copy-changelog:
  #   description: 'If set to true, will compile CHANGELOG.md in the docs homepage'
  #   default: false
  token:
    required: true
    description: Used to work with git. Since there's a default, this is typically not supplied by the user.
    default: ${{ github.token }}
  strategy:
    required: true
    description: The strategy to use to fetch the version. Currently, "tag" and "lerna" are supported.
    default: 'tag'
  
  versions-sorting:
    required: true
    description: "The strategy to use to sort the versions in the list. Possible values:
      - `semver-desc`: sorts by semver descending.
      - `semver-asc`: sorts by semver ascending.
      - `timestamp-desc`: sorts by release timestamp (based on the run that generated a specific build) descending.
      - `timestamp-asc`: sorts by release timestamp (based on the run that generated a specific build) ascending.
    "
    default: 'timestamp-desc'
  enable-prereleases: 
    required: true
    description: Split the versions list into two separate lists of releases and prereleases, using `semver`.
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/docs-publisher/index.js'